(() => {
  const $=id=>document.getElementById(id); const cfg=window.SEZONCHIK_SUPABASE||{};
  const configured=cfg.url && cfg.publishableKey && !cfg.publishableKey.includes('PASTE_');
  if(!configured){$('configPanel').classList.remove('hidden');$('connectionStatus').textContent='Подключение не настроено';return}
  const db=window.supabase.createClient(cfg.url,cfg.publishableKey); let products=[];
  const slugify=s=>String(s||'').toLowerCase().replaceAll('ё','e').replace(/[^a-zа-я0-9]+/gi,'-').replace(/^-|-$/g,'').slice(0,80);
  const money=n=>new Intl.NumberFormat('ru-RU').format(n||0)+' ₽';
  async function boot(){const {data:{session}}=await db.auth.getSession();session?showApp():showLogin();db.auth.onAuthStateChange((_e,s)=>s?showApp():showLogin())}
  function showLogin(){$('loginPanel').classList.remove('hidden');$('app').classList.add('hidden');$('connectionStatus').textContent='Требуется вход'}
  async function showApp(){$('loginPanel').classList.add('hidden');$('app').classList.remove('hidden');$('connectionStatus').textContent='Supabase подключён';await loadProducts()}
  $('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginStatus').textContent='Входим…';const {error}=await db.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});$('loginStatus').textContent=error?error.message:'Готово'});
  $('logout').addEventListener('click',()=>db.auth.signOut());
  async function uploadImage(file){if(!file)return $('existingImage').value||'';const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;const {error}=await db.storage.from(cfg.bucket||'products').upload(path,file,{cacheControl:'3600',upsert:false});if(error)throw error;return db.storage.from(cfg.bucket||'products').getPublicUrl(path).data.publicUrl}
  $('imageFile').addEventListener('change',()=>{const f=$('imageFile').files[0];if(!f)return;const u=URL.createObjectURL(f);$('imagePreview').src=u;$('imagePreview').classList.remove('hidden')});
  $('productForm').addEventListener('submit',async e=>{e.preventDefault();const btn=$('saveButton');btn.disabled=true;$('formStatus').textContent='Сохраняем…';try{const image=await uploadImage($('imageFile').files[0]);const row={title:$('title').value.trim(),slug:slugify($('title').value),category:$('category').value,product_type:$('productType').value,price:+$('price').value||0,old_price:+$('oldPrice').value||null,wheel_size:$('wheelSize').value.trim(),frame_size:$('frameSize').value.trim(),frame_material:$('frameMaterial').value,brakes:$('brakes').value,speeds:+$('speeds').value||null,description:$('description').value.trim(),image,gallery:[],in_stock:$('inStock').checked,published:$('published').checked,featured:$('featured').checked,bestseller:$('bestseller').checked,sort_order:+$('sortOrder').value||0};const id=$('productId').value;const q=id?db.from('products').update(row).eq('id',id):db.from('products').insert(row);const {error}=await q;if(error)throw error;$('formStatus').textContent='Сохранено';resetForm();await loadProducts()}catch(err){$('formStatus').textContent='Ошибка: '+err.message}finally{btn.disabled=false}});
  function resetForm(){$('productForm').reset();$('productId').value='';$('existingImage').value='';$('imagePreview').classList.add('hidden');$('formTitle').textContent='Добавить товар';$('inStock').checked=true;$('published').checked=true;$('sortOrder').value=0}
  $('resetForm').addEventListener('click',resetForm);
  async function loadProducts(){const {data,error}=await db.from('products').select('*').order('sort_order',{ascending:true}).order('id',{ascending:true});if(error){$('productList').innerHTML=`<p>Ошибка: ${error.message}</p>`;return}products=data||[];render()}
  function render(){const q=$('adminSearch').value.toLowerCase();const list=products.filter(p=>(p.title||'').toLowerCase().includes(q));$('productCount').textContent=list.length;$('productList').innerHTML=list.map(p=>`<article class="admin-card"><img src="${p.image||'assets/category-bicycles-new.webp'}" alt=""><div><h3>${p.title||'Без названия'}</h3><p>${money(p.price)} · ${p.wheel_size||'—'}″ · ${p.in_stock?'В наличии':'Уточнять'}</p></div><div class="card-buttons"><button class="secondary" data-edit="${p.id}">Изменить</button><button class="danger" data-delete="${p.id}">Удалить</button></div></article>`).join('')||'<p>Товаров пока нет.</p>'}
  $('adminSearch').addEventListener('input',render);$('refreshList').addEventListener('click',loadProducts);
  $('productList').addEventListener('click',async e=>{const edit=e.target.dataset.edit,del=e.target.dataset.delete;if(edit){const p=products.find(x=>String(x.id)===edit);if(!p)return;const map={productId:p.id,title:p.title,category:p.category||'bicycles',productType:p.product_type||'adult',price:p.price,oldPrice:p.old_price||'',wheelSize:p.wheel_size||'',frameSize:p.frame_size||'',frameMaterial:p.frame_material||'other',brakes:p.brakes||'other',speeds:p.speeds||'',sortOrder:p.sort_order||0,description:p.description||'',existingImage:p.image||''};Object.entries(map).forEach(([k,v])=>$(k).value=v);$('inStock').checked=!!p.in_stock;$('published').checked=p.published!==false;$('featured').checked=!!p.featured;$('bestseller').checked=!!p.bestseller;if(p.image){$('imagePreview').src=p.image;$('imagePreview').classList.remove('hidden')}$('formTitle').textContent='Изменить товар';scrollTo({top:0,behavior:'smooth'})}if(del&&confirm('Удалить товар?')){const {error}=await db.from('products').delete().eq('id',del);if(error)alert(error.message);else loadProducts()}});
  $('importSeed').addEventListener('click',async()=>{if(products.length&&!confirm('В базе уже есть товары. Всё равно добавить текущий каталог?'))return;$('importStatus').textContent='Импортируем…';try{const seed=await fetch('data/seed-products-v70.json').then(r=>r.json());const {error}=await db.from('products').upsert(seed,{onConflict:'slug',ignoreDuplicates:true});if(error)throw error;$('importStatus').textContent='Каталог импортирован';await loadProducts()}catch(err){$('importStatus').textContent='Ошибка: '+err.message}});
  boot();
})();
