document.addEventListener('DOMContentLoaded', () => {
  const grid=document.getElementById('bikeGrid'); if(!grid) return;
  const cards=[...grid.querySelectorAll('.bike-card')];
  const originalOrder=new Map(cards.map((c,i)=>[c,i]));
  const count=document.getElementById('resultCount'), search=document.getElementById('searchInput');
  const wheel=document.getElementById('wheelFilter'), price=document.getElementById('priceFilter'), material=document.getElementById('materialFilter'), brake=document.getElementById('brakeFilter'), speed=document.getElementById('speedFilter'), availability=document.getElementById('availabilityFilter'), sort=document.getElementById('sortFilter');
  const more=document.getElementById('loadMore'), reset=document.getElementById('resetFilters'), toggle=document.getElementById('filterToggle'), fields=document.getElementById('filterFields');
  let category='all', limit=16;
  const normalize=v=>String(v||'').toLowerCase().replaceAll('ё','е').replaceAll(',','.').trim();
  const matchesPrice=(p,r)=>r==='all'||(()=>{const [a,b]=r.split('-').map(Number);return p>=a&&p<=b})()
  function apply(resetLimit=true){if(resetLimit)limit=16;const q=normalize(search.value);let filtered=cards.filter(c=>{const p=Number(c.dataset.price||0);return(category==='all'||c.dataset.category===category)&&(wheel.value==='all'||c.dataset.wheel===wheel.value)&&(material.value==='all'||c.dataset.material===material.value)&&(brake.value==='all'||c.dataset.brake===brake.value)&&(speed.value==='all'||c.dataset.speedGroup===speed.value)&&(availability.value==='all'||c.dataset.availability===availability.value)&&matchesPrice(p,price.value)&&normalize(c.dataset.search).includes(q)});if(sort.value==='price-asc')filtered.sort((a,b)=>+a.dataset.price-+b.dataset.price);else if(sort.value==='price-desc')filtered.sort((a,b)=>+b.dataset.price-+a.dataset.price);else filtered.sort((a,b)=>originalOrder.get(a)-originalOrder.get(b));cards.forEach(c=>c.hidden=true);filtered.slice(0,limit).forEach(c=>{c.hidden=false;grid.appendChild(c)});count.textContent=filtered.length;more.hidden=filtered.length<=limit}
  document.querySelectorAll('.category-tabs [data-category]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.category-tabs [data-category]').forEach(x=>x.classList.remove('active'));b.classList.add('active');category=b.dataset.category;apply()}));
  [wheel,price,material,brake,speed,availability,sort].forEach(x=>x.addEventListener('change',()=>{syncQuick();apply()})); search.addEventListener('input',()=>apply()); more.addEventListener('click',()=>{limit+=16;apply(false)});
  reset.addEventListener('click',()=>{category='all';document.querySelectorAll('.category-tabs [data-category]').forEach(x=>x.classList.toggle('active',x.dataset.category==='all'));[wheel,price,material,brake,speed,availability].forEach(x=>x.value='all');sort.value='default';search.value='';syncQuick();apply()});
  document.querySelectorAll('.view-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.view-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');grid.classList.toggle('list-view',b.dataset.view==='list')}));
  if(toggle&&fields)toggle.addEventListener('click',()=>{const open=fields.classList.toggle('open');toggle.setAttribute('aria-expanded',open);toggle.querySelector('span').textContent=open?'▲':'▼'});
  function syncQuick(){document.querySelectorAll('[data-wheel-quick]').forEach(b=>b.classList.toggle('active',b.dataset.wheelQuick===wheel.value))}
  document.querySelectorAll('[data-wheel-quick]').forEach(b=>b.addEventListener('click',()=>{wheel.value=b.dataset.wheelQuick;syncQuick();apply();document.getElementById('bikeGrid').scrollIntoView({behavior:'smooth',block:'start'})}));
  const selected=new Set(), float=document.getElementById('compareFloat'), n=document.getElementById('compareCount');
  function updateCompare(){n.textContent=selected.size;float.hidden=selected.size===0;cards.forEach(c=>{const cb=c.querySelector('.compare-input');cb.checked=selected.has(c);c.classList.toggle('selected-compare',selected.has(c))})}
  cards.forEach(c=>{
    const openCard=()=>{const href=c.dataset.href;if(!href)return;if(/^https?:/.test(href))window.open(href,'_blank','noopener');else location.href=href};
    c.addEventListener('click',e=>{if(e.target.closest('a,button,input,label'))return;openCard()}); c.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest('button,input')){e.preventDefault();openCard()}});
    c.querySelector('.compare-input').addEventListener('change',e=>{e.stopPropagation();if(e.target.checked){if(selected.size>=3){e.target.checked=false;alert('Можно сравнить максимум 3 велосипеда');return}selected.add(c)}else selected.delete(c);updateCompare()});
    c.querySelector('.zoom-btn').addEventListener('click',e=>{e.stopPropagation();const img=c.querySelector('img');document.getElementById('largeBikeImage').src=img.src;document.getElementById('largeBikeImage').alt=img.alt;document.getElementById('imageModal').hidden=false;document.body.classList.add('modal-open')});
    c.querySelector('.share-btn').addEventListener('click',async e=>{e.stopPropagation();const name=c.querySelector('h2').textContent, url=c.dataset.href&& !/^https?:/.test(c.dataset.href)?new URL(c.dataset.href,location.href).href:location.href;try{if(navigator.share)await navigator.share({title:name,text:'Посмотри этот велосипед в магазине Сезонщик',url});else{await navigator.clipboard.writeText(url);alert('Ссылка скопирована')}}catch(_){}})
  });
  document.getElementById('clearCompare').addEventListener('click',()=>{selected.clear();updateCompare()});
  document.getElementById('openCompare').addEventListener('click',()=>{const chosen=[...selected];const rows=[['Цена',c=>c.querySelector('.bike-price').textContent],['Колёса',c=>c.dataset.wheel+'″'],['Рама',c=>({aluminum:'Алюминий',steel:'Сталь',magnesium:'Магниевый сплав'}[c.dataset.material]||'Другое')],['Тормоза',c=>({hydraulic:'Гидравлические',disc:'Дисковые',rim:'Ободные'}[c.dataset.brake]||'Другие')],['Скорости',c=>c.dataset.speeds||'—'],['Наличие',c=>c.dataset.availability==='stock'?'В наличии':'Уточняйте']];document.getElementById('compareTableWrap').innerHTML=`<div class="compare-scroll"><table><thead><tr><th>Параметр</th>${chosen.map(c=>`<th><img src="${c.querySelector('img').src}" alt=""><span>${c.querySelector('h2').textContent}</span></th>`).join('')}</tr></thead><tbody>${rows.map(([l,f])=>`<tr><td>${l}</td>${chosen.map(c=>`<td>${f(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;document.getElementById('compareModal').hidden=false;document.body.classList.add('modal-open')});
  document.querySelectorAll('[data-close-modal]').forEach(x=>x.addEventListener('click',()=>{document.getElementById('compareModal').hidden=true;document.body.classList.remove('modal-open')}));
  document.querySelectorAll('[data-close-image]').forEach(x=>x.addEventListener('click',()=>{document.getElementById('imageModal').hidden=true;document.body.classList.remove('modal-open')}));
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelectorAll('.v64-modal').forEach(m=>m.hidden=true);document.body.classList.remove('modal-open')}});
  const menuToggle=document.querySelector('.menu-toggle');if(menuToggle)menuToggle.addEventListener('click',()=>document.querySelector('.mobile-menu').classList.toggle('open'));
  apply(); updateCompare();
});